import type {
  AchievementItem,
  GalleryItem,
  PublicationItem,
  ResearchItem,
  TeachingItem,
  CollectionConfig,
} from '../types/content';

export const researchConfig: CollectionConfig<ResearchItem> = {
  id: 'research',
  title: 'Research Projects',
  description: 'Manage research topics, summaries, media assets, and supporting documents.',
  collectionPath: 'research',
  sortBy: 'title',
  sortDirection: 'asc',
  searchableFields: ['title', 'category', 'description', 'objectives', 'methodology', 'results', 'status'],
  defaults: {
    title: '',
    slug: '',
    category: '',
    description: '',
    objectives: '',
    methodology: '',
    results: '',
    status: 'Active',
    imageUrls: [],
    fileUrls: [],
    featured: false,
  },
  fields: [
    { name: 'title', label: 'Research Title', type: 'text', required: true },
    { name: 'slug', label: 'Slug', type: 'text', helperText: 'Used for search and identifiers.' },
    { name: 'category', label: 'Category', type: 'text', required: true },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'objectives', label: 'Objectives', type: 'textarea', required: true },
    { name: 'methodology', label: 'Methodology', type: 'textarea', required: true },
    { name: 'results', label: 'Results', type: 'textarea', required: true },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      options: [
        { label: 'Draft', value: 'Draft' },
        { label: 'Active', value: 'Active' },
        { label: 'Completed', value: 'Completed' },
      ],
    },
    { name: 'featured', label: 'Add in highlights', type: 'toggle' },
    { name: 'imageUrls', label: 'Research Images', type: 'image', multiple: true, accept: 'image/*' },
    { name: 'fileUrls', label: 'Research Files', type: 'file', multiple: true, accept: '.pdf,.doc,.docx,.ppt,.pptx' },
  ],
  preview: (item) => item.description,
  badge: (item) => item.status,
};

export const publicationConfig: CollectionConfig<PublicationItem> = {
  id: 'publications',
  title: 'Publications',
  description: 'Manage journals, conference papers, DOI links, PDFs, and citation data.',
  collectionPath: 'publications',
  sortBy: 'year',
  sortDirection: 'desc',
  searchableFields: ['title', 'authors', 'venue', 'type', 'abstract', 'keywords', 'citation'],
  defaults: {
    title: '',
    slug: '',
    authors: '',
    venue: '',
    year: new Date().getFullYear(),
    type: 'Journal',
    doi: '',
    pdfUrl: '',
    abstract: '',
    keywords: [],
    citation: '',
    bibtex: '',
    featured: false,
  },
  fields: [
    { name: 'title', label: 'Paper Title', type: 'text', required: true },
    { name: 'slug', label: 'Slug', type: 'text' },
    { name: 'authors', label: 'Authors', type: 'textarea', required: true },
    { name: 'venue', label: 'Conference / Journal', type: 'text', required: true },
    { name: 'year', label: 'Year', type: 'number', required: true },
    {
      name: 'type',
      label: 'Type',
      type: 'select',
      required: true,
      options: [
        { label: 'Journal', value: 'Journal' },
        { label: 'Conference', value: 'Conference' },
        { label: 'Book Chapter', value: 'Book Chapter' },
        { label: 'Workshop', value: 'Workshop' },
        { label: 'Patent', value: 'Patent' },
      ],
    },
    { name: 'doi', label: 'DOI', type: 'url' },
    { name: 'pdfUrl', label: 'PDF', type: 'file', accept: '.pdf' },
    { name: 'abstract', label: 'Abstract', type: 'textarea', required: true },
    { name: 'keywords', label: 'Keywords', type: 'tags', helperText: 'Comma-separated keywords.' },
    { name: 'citation', label: 'Citation', type: 'textarea', required: true },
    { name: 'bibtex', label: 'BibTeX', type: 'textarea', required: true },
    { name: 'featured', label: 'Featured', type: 'toggle' },
  ],
  preview: (item) => item.venue,
  badge: (item) => String(item.year),
};

export const teachingConfig: CollectionConfig<TeachingItem> = {
  id: 'teaching',
  title: 'Teaching',
  description: 'Manage course history, semesters, and teaching summaries.',
  collectionPath: 'teaching',
  sortBy: 'year',
  sortDirection: 'desc',
  searchableFields: ['courseName', 'courseCode', 'semester', 'description'],
  defaults: {
    courseName: '',
    courseCode: '',
    semester: '',
    year: new Date().getFullYear(),
    description: '',
    credits: '',
    level: '',
  },
  fields: [
    { name: 'courseName', label: 'Course Name', type: 'text', required: true },
    { name: 'courseCode', label: 'Course Code', type: 'text', required: true },
    { name: 'semester', label: 'Semester', type: 'text', required: true },
    { name: 'year', label: 'Year', type: 'number', required: true },
    { name: 'credits', label: 'Credits', type: 'text' },
    { name: 'level', label: 'Level', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
  ],
  preview: (item) => item.courseCode,
  badge: (item) => `${item.semester} ${item.year}`,
};

export const galleryConfig: CollectionConfig<GalleryItem> = {
  id: 'gallery',
  title: 'Gallery',
  description: 'Upload and manage event images, conference moments, and award shots.',
  collectionPath: 'gallery',
  sortBy: 'year',
  sortDirection: 'desc',
  searchableFields: ['title', 'category', 'description'],
  defaults: {
    title: '',
    category: '',
    imageUrl: '',
    description: '',
    year: new Date().getFullYear(),
    featured: false,
  },
  fields: [
    { name: 'title', label: 'Title', type: 'text', required: true },
    { name: 'category', label: 'Category', type: 'text', required: true },
    { name: 'imageUrl', label: 'Image', type: 'image', accept: 'image/*' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'year', label: 'Year', type: 'number', required: true },
    { name: 'featured', label: 'Featured', type: 'toggle' },
  ],
  preview: (item) => item.description,
  badge: (item) => item.category,
};

export const achievementConfig: CollectionConfig<AchievementItem> = {
  id: 'achievements',
  title: 'Achievements',
  description: 'Keep the quantified highlights that appear on the homepage.',
  collectionPath: 'achievements',
  sortBy: 'title',
  sortDirection: 'asc',
  searchableFields: ['title', 'value', 'description'],
  defaults: {
    title: '',
    value: '',
    description: '',
    icon: '',
  },
  fields: [
    { name: 'title', label: 'Title', type: 'text', required: true },
    { name: 'value', label: 'Value', type: 'text', required: true },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'icon', label: 'Icon Name', type: 'text', helperText: 'Optional string label used by the UI.' },
  ],
  preview: (item) => item.description,
  badge: (item) => item.value,
};
